version: '3.9'
services:

  # 服务名
  frps-docker:
    # 模拟一个伪终端
    tty: true
    # 打开标准输入,可以接受外部输入
    stdin_open: true
    # 指定容器中运行应用的用户名
    user: root
    # 主机名
    hostname: frps-docker
    # 指定容器名称
    container_name: frps-docker
    # 指定为镜像名称或镜像ID
    image: danxiaonuo/frps-docker:latest
    # 覆盖容器启动后默认执行的命令
    # command: /sbin/init
    # 允许容器中运行一些特权命令
    privileged: true
    # 指定容器退出后的重启策略为始终重启
    restart: always
    # 指定容器的内核能力(capacity)分配
    cap_add:
     - ALL
    # 配置容器内核参数
    sysctls:
     - net.ipv4.tcp_ecn=1
     - net.ipv4.tcp_ecn_fallback=1
     - net.ipv4.tcp_congestion_control=bbrplus
    # 数据卷所挂载路径设置
    volumes:
      # 配置目录与文件
      - ./conf/frp/frps.ini:/etc/frp/frps.ini:rw,cached
      # 日志目录
      - ./logs/frp:/var/log/frps.log:delegated
      # 同步宿主机时区与时间
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      # 共享内核
      #- /lib/modules:/lib/modules:ro,cached
      #- /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    # 指定设备映射关系
    devices:
     - /dev/net/tun
    # 配置容器连接的网络
    network_mode: "host"
    # 指定容器的 ulimits 限制值
    ulimits:
      nproc: 65535
      nofile:
          soft: 65535
          hard: 65535
